# Generated by Django 3.1.5 on 2021-01-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baselisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.category'),
        ),
    ]
